name: Auto PR and Tweet
on:
  push:
    branches-ignore:
      - main
      - master
jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Extract project info
        id: project-info
        run: |
          # Extract project name from branch name
          PROJECT_NAME=$(echo ${{ github.ref_name }} | grep -oP 'project\d+' | tr '[:lower:]' '[:upper:]')
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_OUTPUT
          
          # Extract the main part of the commit message after "feat: "
          echo "COMMIT_DESC=$(echo '${{ github.event.head_commit.message }}' | sed 's/^feat: //')" >> $GITHUB_OUTPUT
          
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Auto PR: ${{ github.ref_name }}'
          body: |
            **${{ steps.project-info.outputs.PROJECT_NAME }}**: ${{ steps.project-info.outputs.COMMIT_DESC }}
            **Tech stack**: React, Tailwindcss
        
          base: main
          branch: ${{ github.ref }}
          draft: false
